package exceptionHandling;

public class MultipleCatch {

	public static void main(String[] args) {
		int value[] = {3,6,8,4,9};
		
		try {
			System.out.println(1/0);
			
		} catch (ArithmeticException a) {
			System.out.println(a);
			System.out.println(10/5);
		}
		catch (Exception e) {
			System.out.println(e);
			
			
			
		try {
				System.out.println(10/2);
				
			} catch (ArithmeticException a) {
				System.out.println(a);
				System.out.println(10/5);
			}
			catch (Exception w) {
				System.out.println(w);
		
		}
		
				
		System.out.println("Program is successful");

	}
	

}

